export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_PENDING = 'DELETE_ITEM_PENDING';
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';

export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_PENDING = 'ADD_ITEM_PENDING';
export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';
