export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';
export const SET_AUTH_PENDING = 'SET_AUTH_PENDING';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_PENDING = 'ADD_USER_PENDING';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const CLEAN_USER = 'CLEAN_USER';

