export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';
export const SET_AUTH_PENDING = 'SET_AUTH_PENDING';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';

// export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
