export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERID_SUCCESS = 'GET_ORDERID_SUCCESS';
export const GET_ORDERS_PENDING = 'GET_ORDERS_PENDING';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';

export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_PENDING = 'ADD_ORDER_PENDING';
export const ADD_ORDER_ERROR = 'ADD_ORDER_ERROR';

export const EDIT_ORDER_SUCCESS = 'EDIT_ORDER_SUCCESS';
export const EDIT_ORDER_PENDING = 'EDIT_ORDER_PENDING';
export const EDIT_ORDER_ERROR = 'EDIT_ORDER_ERROR';

export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_PENDING = 'DELETE_ORDER_PENDING';
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR';